### ISSUE TITLE
No telemetry with TD-18 receiver from external GPS logger

### ISSUE THREAD

**Issue by keiner0815** [FrSkyRC/ETHOS-Feedback-Community#2195]
I tried to connect an Unisense GPS logger to a TD-R18.

To confirm the GPS logger is set up und working correctly I connected it to Access SR8 Pro with no problem. When searching for sensors all the values will come up immediately.

But when I connect it to the TD-R18 it does not find any telemetry value when searching for sensors.

In the HF-settings tab I scrolled down to the settings button of the TD-R18 and configured pin 18 as "S.Port" pin (also tried it with ch1, ch16, ch17) but there are no telemetry connection.

HF power on the 868 Mhz frequency is set to 25mW and telemetry is also activated in the TD-R18 settings.

So I would think this is a bug or am I doing something wrong?

**Comment by mawzthefinn** [comment]
The TD series receivers are known to require strict adherence to the S.Port spec or sensors will not work. The Archers are looser about compliance.

Unisens sensors are known to have some issues with S.Port compliance on older firmware.

This is a bug, but it's a Unisens bug almost assuredly. Similar issues have been noted with the Unisens-E sensor and corrected by firmware updates from the vendor.

I would recommend contacting the vendor of the Unisens GPS logger.

**Comment by keiner0815** [comment]
I tested a Unisense-E also and the problem remains the same.
Unisense-E and GPS logger both work with every other Frsky receiver, just not with the TD-R18.
There is no newer firmware for the GPS logger.

If every receiver I have works with the Unisense sensors, except for the TD-R18, for me the TD-R18 receiver is the problem.
(I get what you are saying, but why would FrSky change the S.Port handling?)

**Comment by mawzthefinn** [comment]
Is your Unisens-E running the latest (beta) firmware? Or older firmware? 

FrSky tightened up the timing to closer align with the published spec for the TD's. This was well sorted out by Simon Wood earlier this year when his sensors (RC Light Systems ESC Telemetry Converter) had issues. 

Also note that on the TD R10 and R18 receivers the 4-pin header does not work as a telemetry connector, only the designated 3-pin servo port.

**Comment by mawzthefinn** [comment]
OK, you're definitely configured correctly on the TD R18 side. 

If you can try the updated Unisens-E, that would be great. If it works then the GPS Logger probably just needs to be reported to the vendor so they can apply the same fix in their firmware (they probably won't know there's an issue until somebody complains).

**Comment by glipski50** [comment]
The fix that was provided for the Unisense was to allow to change the app id in the case the Unisense was connected to a Archer GR receiver. In that configuration a sensor conflict was generated since Unisense and GR receiver used the same app id for vspd and alt. Since the TD receiver does not have a baro sensor such a conflict will not be generated. The problem must have a different cause. I have asked the German Frsky distributor if he can recreate the problem since he also distributes the GPSLogger, Unisense and other sensors from sm-modellbau.

**Comment by glipski50** [comment]
I talked to Mr. Merz, the owner of sm-modellbau. He already has a beta firmware GL2v129a for the GPSLogger 3 that adresses the TD receiver. He can provide this firmware per email on request. Through the next winter month he will provide an official update for all his sensors.

**Comment by mawzthefinn** [comment]
Closing off as the solution has been identified. Please contact Mr. Merz @ SM-Modellbau for the updated firmware.
