### ISSUE TITLE
My Tandem XE-S hangs when i use Ethos Suite I need to remove the battery to restart it.

### ISSUE THREAD

**Issue by ola-aberg** [FrSkyRC/ETHOS-Feedback-Community#2251]
I start the Ethos Suite and puts the transmitter in bootloader mode and connect the usb cable and the display shows USB connected. In Ethos Suite i get Radio connection is not detected. I unplug the usb cable from the transmitter but the display still shows USB connected. Can't turn off the transmitter so I need to remove the battery.

I put the transmitter in bootloader mode again and connect the usb cable and the display shows USB connected. Now Ethos Suite finds the transmitter. This does not happen every time but maybe 6 times in a short time.

Tandem EX-S
Bootloader ver 1.4.4
Firmware 1.4.4
Ethos Suite 1.4.4 and Ethos Suite 1.4.5

/ Ola

**Comment by mawzthefinn** [comment]
By any chance are you running betaflight configurator or a similar app? I ran into a similar issue and it turned out to be BF Configurator grabbing the USB port when it was running.

**Comment by ola-aberg** [comment]
No i don't. The programs that are usually running when I connect the transmitter are Firefox, File Explorer Adobe Acrobat and Ethos Suite. Sometimes Computer Management / Device Manager may be running  as well. I have had the transmitter connected to the Ethos Suite twice after registering the case. No update just backups.

I registered the case to see if there were others with the same problem it's not a big problem for me.
It may have been resolved with the last update I did yesterday, I will wait and see what happens.

/ Ola

**Comment by Dsrenger** [comment]
I can confirm Ola.

I have a X20S and it never hang up. Never needed to pull the battery plug.

Now I have additionally the XE-S and need to pull the plug in 80% of the cases.

Same behavior as Ola.

XE-S in Bootloader Mode. Attach it to the PC with the Suite open. The Radio is not detected. Unplug the cable. The display still shows USB connected. Pull Battery. Go into Bootloader Mode. Reattach to the PC and everything works fine.

Never had AND have it with my X20s.

Thought its strange, but with reading Ola's post I thought and write my experience as well.

**Comment by Dsrenger** [comment]
Same again updating to 1.4.6

X20s works like a charm.
XEs hang up.

Doubt its a computer issue, as the X20s is always working without any problems and the XEs always hangs up.

**Comment by yak-54** [comment]
i had this happen  to me 2 or 3 times as well with X12S just hangs using ethos suit 1.4.6 i had pull the back off to remove battery

**Comment by yak-54** [comment]
Have you tried to update it manually with out ethos suite ?

**Comment by Jepelisa** [comment]
I have the same radio XE-S and the same problems since updating 1.4.6.
I have noted that releases for "flash" and "sd card" are never published since this radio exist.
