### ISSUE TITLE
RB25/25S Luas are not working real good

### ISSUE THREAD

**Issue by EngelMT** [FrSkyRC/ETHOS-Feedback-Community#4109]
I'm not sure if it's an ETHOS problem. But here in our forum (over 8000 members) and in RCG this topic is discussed very seriously. The Luas of the RB25/25S are not running properly. You have to de-energise the RB more often for the Lua to start at all and when it is running, some fields are greyed out and therefore not usable.

**Comment by Chilie78** [comment]
Yeah I reported this a little more than 3 weeks ago as linked to here:
https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/4003
This has been going on for a while now and it seems that fixing this isn't that big of a priority at the moment. I see more features being added than bugs being fixed at the moment.

**Comment by EngelMT** [comment]
@Chilie78 I know that Bertrand will work on it.

**Comment by Kreisflieger** [comment]
This sound promising. When Bertrand finds the time to dig into this problem, I am sure we will get a working solution in a short period of time.
Many thanks in advance to Bertrand.

**Comment by Kreisflieger** [comment]
Still missing:
If failsafe for CH 14 is set to -100% ( LUA Config, page 3 ), the RB25S should switch into Automatic Mode. All  recent Archer, TD and TW stabilization-receivers  are capable of doing this. Currently the RB25s not!

**Comment by Chilie78** [comment]
I would be happy to wait for a fix, but until I see that someone has been assigned to work on this task, I will continue to be annoyed at the whole situation. I know not a lot of people are running the RB series compared to the regular receivers. Then I would say don't sell alpha hardware or at least require resellers to say "Software is still under development". It erks me something seriously that I blew 200+ bucks on hardware that I cannot use or return.

**Comment by Kreisflieger** [comment]
Please see also my Issue from March 28, 2024:

**RB25s does not switch into automatic mode in case of failsafe , channel 14 = -100%**

[ https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/3731 ](url)

**Comment by Nicholas-Luoyi** [comment]
For now you could change `return field` into `return nil` in `createStaticText` function if you are urgent to use it. The official version will soon come out

**Comment by Kreisflieger** [comment]
Hello Nicholas,
thanks for your advise.  I did the change in the LUA.

At least on page one of the RB5/25s Config, all fields are hightlighted, and can be changed !

Failsafe with CH14 on -100% seems to work for just a second, then all servos are back to neutral.

So I will wait for the official new FW and LUAs.

Kind regards Stephan

**Comment by bsongis-frsky** [comment]
Please download again the Lua scripts for RB25/RB25S.
Nicholas has fixed 2 issues

**Comment by Kreisflieger** [comment]
Hello Bertrand,

I downloaded the new LUAs from the FrSky Download page.

The RB25/ 25S Config seems to work ok.

Failsafe still does not switch to Automatic Mode if CH 14 = -100%.

Please have another look to the RB 25S.

Thanks in advance 

Stephan

**Comment by Kreisflieger** [comment]
Thanks !!!!!

**Comment by Nicholas-Luoyi** [comment]
RB 25S doesn't support this feature for now. And it would be available in the future.

**Comment by bsongis-frsky** [comment]
Closing again the issue then.
