### ISSUE TITLE
 Lua widget key '' not found warning after update to 1.5.8 (request to reopen #4079 )

### ISSUE THREAD

**Issue by fdm225** [FrSkyRC/ETHOS-Feedback-Community#4111]
In issue 4079 the solution was to remove all of the models from the radio, that doesn't really work for me as I have about 20 and really really do not want to recreate them.  could we get this looked at as I checked all of my scripts and they are properly formatted (and I did the same as the user in 4079 where I removed them all).  Doesn't seem feasible that the solution should be to delete everything and start over; that's like really really bad.

dave

**Comment by MiRe-CZ** [comment]
If this message appears only when you activate one model, look at its screens if there is any widget showing "---". If yes, go to configuration and change it first to whatever else (e.g. Value) and then back to unused ("---"}. The issue should be solved, message should not appear any more and the related place on the screen should be empty.

When I got the message after update to 1.5.8 I spent some time by looking into my widgets in vain, but then I discovered this strange item. It is question how it had been created, perhaps during many model conversions

**Comment by strgaltdel** [comment]
As an addition:

There may be cases where all widget frames are defined and the message still appears.

Presumably, in the past,  there was a different widget layout with more frames on the screen.
Then layout was changed to a more "slim layout" without performing a checkout of the now unused widgets

these entries seem to exist as artifacts without a key


it helps to switch temporarily to a layout with more widget frames and to redefine all “empty” frames as described above.

then return to the original layout

**Comment by fdm225** [comment]
I appreciate the manual method but it seems like there should be a software fix for this as you are talking about doing this on a lot of different models.  The procedure that you put out is essentially check each screen of every model (as it happens on all of mine) to see if there is an invalid reference and if there is touch that widget and if there isn't then change the layout loosing what I have setup.  

What I am asking for is a fix in the code that removes invalid references for me.  I know that seems selfish but if I am having this issue and am frustrated by it then others probably are as well.

**Comment by strgaltdel** [comment]
Personally, I don't think your concern is selfish:

This warning became visible after the introduction of the “lua alarm” symbol, was probably initiated a long time ago, but was not obvious.
I read 3..4 comments on a German forum from users who didn't know how to deal with it / how to get around it.
There were also some questions on rcg, so some kind of automatic “cross-check” seems reasonable to me

of course, it doesn't seems to be a "high prio" issue

**Comment by MiRe-CZ** [comment]
Well, I cosider our advices as temporary solutions, where needed. I trust devs take provided information and there will be a solution included into system. Even notification enhanced by concrete information, at least by affected model, would helpBR, Milan

**Comment by bsongis-frsky** [comment]
The affected model is your current model! All other models are not loaded on system startup, so you really have a problem (I think of a deleted script, as written in #4079)

**Comment by fdm225** [comment]
I rechecked everything and Its an unused slot in a layout that doesn’t have a widget assigned.  To make matters more complicated you have to fix the issue and then reload the model to see the results.  Think that this feature should be enhanced to give better details to what the issue is and should not have been closed.

**Comment by RC-SOAR** [comment]
Another data point: 

1. Create a setup on Tx A  running Ethos 1.4.12
2. Transfer setup to Tx B which does not have any third party Lua widgets. Tx B is running 1.5.9.

_Expected_: no error message (since no widgets to fail)
_Actual_: Tx B displays "Lua widget key not found" + red triangle. Not just for new model, but for *all* models (perhaps because I didn't reboot after selecting a different model). 

The solution was to change the layout of screen1 in Tx B. Then the message disappears for all models (after reboot). 

A more meaningful error message would help, and also the message should only appear against the affected model (it should not be necessary to reboot in order to clear the message).

Model file from step 1 attached:
[dlg200x.bin.txt](https://github.com/user-attachments/files/15804767/dlg200x.bin.txt)
