### ISSUE TITLE
With 2 ailerons on two channels, can only adjust subtrim on one and not the other

### ISSUE THREAD

**Issue by legalmachinist** [FrSkyRC/ETHOS-Feedback-Community#4522]
My issue deals with 2 servo (and therefor 2 channel) ailerons.  They are on channels 1,5 as the X20S radio (running the latest version as of today - 1.5.15) normally assigns.  I can adjust either subtrim or PWM centering (an excellent option) on channel 1 with no problem.  However, when I do so, it also adjusts (wrongly) the channel 5 servo - so fixing one screws up the other.  And, attempting to adjust the channel 5 subtrim and PWM centering to counter, does nothing.  Changing aileron from channel 5 to channel 6 does not improve it, subtrim/centering does still not work.    Changing the model edit to a single aileron (rather than 2) also does not free channel 5 from channel 1 (and interestingly enough, still operates as if it were still designated as 2 aileron servos when I expected only the channel  one aileron servo to operate.   Trying to get everything perfect having only mechanical aspects to adjust is not only incredibly time consuming but all but near impossible as the mechanical adjustments are far coarser than changing the signals in the radio.  This seems to be a real software bug unless someone can educate me on what I do wrong.  Thank you.  M

**Comment by Tsubasa2024** [comment]
If you are adjusting Aileron by the trim switch below the sticks, it is adjusting the aileron input which will translate into the corresponding motion of the 2 aileron channels.  If subtrim is done at the output pages for channel 1 and 5 one by one, they should be separate trim.

**Comment by bsongis-frsky** [comment]
Several options there:
- either you need an offset on your 2 ailerons and you may add the Offset Mix to do so
- or you need really a subtrim, and perhaps you will like to use a Var to have the 2 values synchronized and also allow you to adjust it in flight

**Comment by legalmachinist** [comment]
And that is precisely my point.  The subtrim at the output is Not separate - only channel 1 works and affects both channels.  Channel 5 subtrim does Nothing.On Sep 15, 2024, at 11:24 PM, Tsubasa2024 ***@***.***> wrote:﻿
If you are adjusting Aileron by the trim switch below the sticks, it is adjusting the aileron input which will translate into the corresponding motion of the 2 aileron channels.  If subtrim is done at the output pages for channel 1 and 5 one by one, they should be separate trim.

**Comment by legalmachinist** [comment]
Thanks for your reply.  The problem is the subtrims are synchronized - Wrongly and do not operate separately as I believe they logically should.  Offset is an interesting notion but not sure I know how to implement that.  Not quite independant but could be a workable compromise.MOn Sep 16, 2024, at 5:37 AM, Bertrand Songis @ FrSky ***@***.***> wrote:﻿
Several options there:

either you need an offset on your 2 ailerons and you may add the Offset Mix to do so
or you need really a subtrim, and perhaps you will like to use a Var to have the 2 values synchronized and also allow you to adjust it in flight

**Comment by legalmachinist** [comment]
I don’t understand why this is closed - the separate sub trim feature on ailerons does not work.  You can not adjust the centering of the two aileron servos separately.On Sep 16, 2024, at 5:37 AM, Bertrand Songis @ FrSky ***@***.***> wrote:﻿
Closed #4522 as completed.

**Comment by robthomson** [comment]
The trim button can really only affect both channels. 

Are you sure you are not simply wanting to do an offset on the channel on the output screen?

**Comment by legalmachinist** [comment]
Forget about the trim.  I want to do separate subtrim or PWM centering on each of the two aileron channels independently.  I should be able to do this but the radio doesn’t permit it.  Hence, there is no way to get both servos centered.  This is a fault I am reporting.MOn Sep 17, 2024, at 12:51 PM, Rob Thomson ***@***.***> wrote:﻿
The trim button can really only affect both channels.
Are you sure you are not simply wanting to do an offset on the channel on the output screen?

**Comment by robthomson** [comment]
Have you edited the servo center on the output page?

**Comment by legalmachinist** [comment]
You can only  do it for channel 1 and when you do, it affects channel 5 the wrong direction.  You Can not do it on channel 5 as all is grayed out.  I don’t know how I can be clearer about this!On Sep 17, 2024, at 1:53 PM, Rob Thomson ***@***.***> wrote:﻿
Have you edited the servo center on the output page?

**Comment by legalmachinist** [comment]
And thank you for your response and attention!!On Sep 17, 2024, at 1:53 PM, Rob Thomson ***@***.***> wrote:﻿
Have you edited the servo center on the output page?

**Comment by legalmachinist** [comment]
And did you try it?On Sep 17, 2024, at 1:57 PM, Mark Hofer ***@***.***> wrote:﻿You can only  do it for channel 1 and when you do, it affects channel 5 the wrong direction.  You Can not do it on channel 5 as all is grayed out.  I don’t know how I can be clearer about this!On Sep 17, 2024, at 1:53 PM, Rob Thomson ***@***.***> wrote:﻿
Have you edited the servo center on the output page?

**Comment by robthomson** [comment]
Changing the center on the output screen will not in any way cause the other channel to move.

I think you are editing within the mix - not the outputs screen!

**Comment by legalmachinist** [comment]
Thanks for your note Rob.I and confirm I was on the outputs page - it is the only place, of which I am aware, where one can modify the PWM, the preferred way to center a servo.  And yes, adjusting one aileron should not move the other and yet, it did.  Having power cycled (and flown) the radio a number of times (including just now but not testing while connected to the airplane which is currently packed for travel to an IMAC contest) I can now confirm that the radio will let me modify each PWM independently, as it should, but which was not the case before (both subtrim and PWM on the second aileron channel were previously grayed out).  I find this inexplicable (but am happy) that it is no longer grayed out.  Of course the receiver is not connected and that may change the situation back to what I previously experienced.  As I have trimmed the plane for the best compromise given the prior limitations and will have no opportunity before Saturday’s IMAC event to test/retrim, final proper corrections given this new development will have to wait until next week, regretfully after the contest.I thank you for your patience and persistence.  Maybe all will be fine even with receiver connected although why the system behaved as it did before remains a mystery.  And no, I was not confused about screens.  Will keep you posted when I get a chance next week to do it correctly (assuming the radio cooperates!).M On Sep 19, 2024, at 5:22 PM, Rob Thomson ***@***.***> wrote:﻿
Changing the center on the output screen will not in any way cause the other channel to move.
I think you are editing within the mix - not the outputs screen!

**Comment by robthomson** [comment]
Any chance you are using a gyro receiver?

**Comment by legalmachinist** [comment]
An excellent question but no, they are not allowed in IMAC.  And I just created a new model and PWM adjustments on each of the ailerons worked correctly (although again no receiver was connected.). Absolutely mystifying.MOn Sep 19, 2024, at 6:04 PM, Rob Thomson ***@***.***> wrote:﻿
Any chance you are using a gyro receiver?

**Comment by Tsubasa2024** [comment]
I experienced the same issue around 2 months ago.  So far as i recall, that happened when the channel assignment (my case was split ailerons same as yours) was not done right from the beginning or being changed or added in the middle of the process.  I cannot remember the exact process that i went through.  I recall i fixed it by opening another model file to restart the setting process with channels number and settings being nailed down right from the beginning.  Sent from my iPhoneOn Sep 20, 2024, at 5:58 AM, legalmachinist ***@***.***> wrote:﻿
Thanks for your note Rob.I and confirm I was on the outputs page - it is the only place, of which I am aware, where one can modify the PWM, the preferred way to center a servo.  And yes, adjusting one aileron should not move the other and yet, it did.  Having power cycled (and flown) the radio a number of times (including just now but not testing while connected to the airplane which is currently packed for travel to an IMAC contest) I can now confirm that the radio will let me modify each PWM independently, as it should, but which was not the case before (both subtrim and PWM on the second aileron channel were previously grayed out).  I find this inexplicable (but am happy) that it is no longer grayed out.  Of course the receiver is not connected and that may change the situation back to what I previously experienced.  As I have trimmed the plane for the best compromise given the prior limitations and will have no opportunity before Saturday’s IMAC event to test/retrim, final proper corrections given this new development will have to wait until next week, regretfully after the contest.I thank you for your patience and persistence.  Maybe all will be fine even with receiver connected although why the system behaved as it did before remains a mystery.  And no, I was not confused about screens.  Will keep you posted when I get a chance next week to do it correctly (assuming the radio cooperates!).M On Sep 19, 2024, at 5:22 PM, Rob Thomson ***@***.***> wrote:﻿

Changing the center on the output screen will not in any way cause the other channel to move.

I think you are editing within the mix - not the outputs screen!

**Comment by legalmachinist** [comment]
Thank you for confirming I have not lost my mind!  Not sure I got to the ‘bad place’ the same way you did as I built the model with 2 aileron channels right from the beginning.  At any rate, it seems to have cured itself as of now.  I hope it stays cured!MOn Sep 19, 2024, at 6:54 PM, Tsubasa2024 ***@***.***> wrote:﻿
I experienced the same issue around 2 months ago.  So far as i recall, that happened when the channel assignment (my case was split ailerons same as yours) was not done right from the beginning or being changed or added in the middle of the process.  I cannot remember the exact process that i went through.  I recall i fixed it by opening another model file to restart the setting process with channels number and settings being nailed down right from the beginning.  Sent from my iPhoneOn Sep 20, 2024, at 5:58 AM, legalmachinist ***@***.***> wrote:﻿

Thanks for your note Rob.I and confirm I was on the outputs page - it is the only place, of which I am aware, where one can modify the PWM, the preferred way to center a servo.  And yes, adjusting one aileron should not move the other and yet, it did.  Having power cycled (and flown) the radio a number of times (including just now but not testing while connected to the airplane which is currently packed for travel to an IMAC contest) I can now confirm that the radio will let me modify each PWM independently, as it should, but which was not the case before (both subtrim and PWM on the second aileron channel were previously grayed out).  I find this inexplicable (but am happy) that it is no longer grayed out.  Of course the receiver is not connected and that may change the situation back to what I previously experienced.  As I have trimmed the plane for the best compromise given the prior limitations and will have no opportunity before Saturday’s IMAC event to test/retrim, final proper corrections given this new development will have to wait until next week, regretfully after the contest.I thank you for your patience and persistence.  Maybe all will be fine even with receiver connected although why the system behaved as it did before remains a mystery.  And no, I was not confused about screens.  Will keep you posted when I get a chance next week to do it correctly (assuming the radio cooperates!).M On Sep 19, 2024, at 5:22 PM, Rob Thomson ***@***.***> wrote:﻿



Changing the center on the output screen will not in any way cause the other channel to move.



I think you are editing within the mix - not the outputs screen!

**Comment by robthomson** [comment]
Can you attach a copy of your model memory?

**Comment by legalmachinist** [comment]
Here you go.  Thank you for looking into this.
M


￼

**Comment by legalmachinist** [comment]
Finally got to test the radio now that the second aileron channel’s subtrim and PWM centering are no longer grayed out.  Yes, the numbers can now be changed BUT, there is absolutely No effect on the second servo.  The fundamental problem persists.  I can adjust one aileron channel but not the other.  So disappointed.  And also with the lack of answers to this issue.MOn Sep 20, 2024, at 8:00 AM, Mark Hofer ***@***.***> wrote:﻿Here you go.  Thank you for looking into this.M<67 laser.bin>On Sep 20, 2024, at 12:33 AM, Rob Thomson ***@***.***> wrote:Can you attach a copy of your model memory?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
