### ISSUE TITLE
Ethos 1.6.0-RC1, EU TD SR12 Stabilisation Error

### ISSUE THREAD

**Issue by gjhclough** [FrSkyRC/ETHOS-Feedback-Community#4816]
Using Ethos 1.6.0 RC1 EU, Internal Module HW 1.4.0 FW 3.0.0 (EU-LBT), Receiver TD SR12 HW 1.1.0 FW 3.0.0

Using latest Lua scripts.  Calibration works fine.  Problem with TS/TW SRX stab Lua, using quick mode, Self check does not do anything, unable to set level position, no stabilisation on rudder, just doesn't do anything when receiver is moved.  Auto level partly works, Stabilisation mode doesn't do anything, appears as though stabilisation is off.

**Comment by philippe-warnotte** [comment]
Concerning the modul RF-FW 3.0.0 version, although there is an final version on Ethos suite, 
the receivers FW 3.0.0 is still in BETA version! For me: TW-ISRM 3.0.0

**Comment by mawzthefinn** [comment]
It sounds like you are using the Lua for configuring Firmware 1.1.13/1.1.14, not the new process for FW 3.0.0 which is in Device COnfig

If you've loaded FW 3.0.0 on the receiver, Self-check has been replaced with new functionality which is a MASSIVE improvement.

Make sure you load the Stabilizer Config lua from the Lua Library in Suite 1.6.0, then go to Device Config->Receivers->Stabilizer Config, open the Stabilizer set you are configuring and learn your Level, Stick Centres and Stick Endpoints.

You can now do each part of the old Self-Check independently. Note you do have to do it for each Stabilizer Set individually.

**Comment by philippe-warnotte** [comment]
For RF- FW 3.0.0: Stabilizer config LUA 3.0.0 or 3.0.1 ?
![image](https://github.com/user-attachments/assets/5aa5ab65-e847-4b1e-b6bf-89bd223b95a9)

**Comment by Nicholas-Luoyi** [comment]
I see two topics here in this conversation.

For @gjhclough. I think @mawzthefinn's advice is correct. The new stabilizer config could be found in the device config menu if you install it correctly.

For @philippe-warnotte. I think you need to check if the Tx and Rx are both flashed with firmware above 3.0.0

**Comment by gjhclough** [comment]
Thankyou, feedback was very helpful. I upgraded ETHOS to 1.6.0 RC3, installed the LUA scripts, and used the new device config tool.  This is much more user friendly than the previous approach, and fairly self explanatory.

Auto level now works in quick mode.

However, I can only get AUTO LEVEL on, I. cannot find a way to get STABILISATION to work.  I have tried both the normal quick mode setup, and also tried doing it through a VARS, but the result is the same, on a 3 posistion switch at 
-100% AUTO LEVEL
0% OFF
+100% OFF

Has something changed in terms of getting normal stabilisation (I know this as AS3X) to work ?

Many thanks

**Comment by mawzthefinn** [comment]
The Rate stabilization is pretty subtle, you have to turn the gains WAY up to see it work. I always test it on the ground with CH13 at 100% (max gain)

**Comment by philippe-warnotte** [comment]
"Script Stabilizer Config lua from the Lua Library in Suite 1.6.0"
It would be nice to have a manual to explain the settings of the new stabilization system.

**Comment by gjhclough** [comment]
Apologies for the delay, have been away with work.  I have installed RC5, updated the LUA scripts to the latest versions through ETHOS.  Then done a bench test with a new receiver.
- Setup a new model, Gain Ch13 on POT2, Stab Mode 1 on SA, Stab Mode 2 on SD
- Receiver TD SR12 flashed to 3.0.0
- 6 axis gyro calibration
- Gyro mode set to Basic
- ADV Config set to Disable
- Group 1 Stabilisation on, with Quick Mode Enabled
- Group 2 Stabilisation off

The 3 position SA switch is Auto Level, OFF, OFF.  Not Auto Level, Stabilisation, OFF.

I have checked by turning the gain upto max, stabilisation is definitely not enabled.

Cheers

**Comment by gjhclough** [comment]
Oops, not sure why, but tried it on a different receiver and stabilisation does work.  Reflashed the previous one and that works too.  Is it recommended to leave the gain% rates as default, 

Ail 50%
Ele 80%
Rudd 100%
Ail Auto 1v1 50%
Ele Auto 1v1 80%

Thanks

**Comment by deeallcco** [comment]
Stab 3.0 in Auto level reduces the flight control surfaces overall throws. In just stabilized or off I get full throws. Is there a way to increase the throws in self level from their reduced action? Thanks in advance.

**Comment by mszulen** [comment]
> Stab 3.0 in Auto level reduces the flight control surfaces overall throws. In just stabilized or off I get full throws. Is there a way to increase the throws in self level from their reduced action? Thanks in advance.

Isn't it intentional to leave the stabilizer some room for the corrective movements (you can see same behaviour in iNav or Ardupilot, for example)?

**Comment by deeallcco** [comment]
I got it fixed with a reset and reinstall using 3.0 and 3.01 and all is good. My error
 Thanks. Flies beautifully.

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by gjhclough** [comment]
A new stabilisation issue identified.

Upgraded X20S to RC8.  Receiver TD SR12, updated to firmware 3.0.1, under the device config menu -> receiver, it advises receiver cannot be read.

Downgrading the receiver firmware to 3.0.0, all works again.

**Comment by erichabg** [comment]
Same problem!
Got two new TD SR6 receivers from german distributor. Both with V3.0.1 equiped.
Therefore i updated my X20S with Ethos V1.6.0 and internal module FW 3.0.1.
Then I tried to calibrate the receivers with Device Config -> "unable to read".

**Comment by mawzthefinn** [comment]
Is the new issue still present on the release versions of ETHOS 1.6.0 and Firmware 3.0.1 or later?

**Comment by philippe-warnotte** [comment]
OK for me. Ethos 1.6.1-RC3 , RF FW3.0.1, Lua script Stabilizer Config 3.0.2
